# name: Veracode_Docker_scan
# on:
#   push:
#     branches: [ main ]

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: pipeline

    steps:
      # - name: checkout repo
      #   uses: actions/checkout@v3
      
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out your repository's code
    
      - name: Build Docker image
        run: docker build -t your-image-veracode:latest .

      - name: List of images
        run: docker image ls

      - name: Veracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.1
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          command: "scan" 
          type: "image"
          source: "your-image-veracode:latest"
          format: json
          debug: true
          fail_build: false
